// dog breeds courtesy: https://www.akc.org/dog-breeds/

let dogBreeds = [
    {name: "Affenpinscher",link: "https://www.akc.org/dog-breeds/affenpinscher/"},
    {name: "Afghan Hound",link: "https://www.akc.org/dog-breeds/afghan-hound/"},
    {name: "Airedale Terrier",link: "https://www.akc.org/dog-breeds/airedale-terrier/"},
    {name: "Akita",link: "https://www.akc.org/dog-breeds/akita/"},
    {name: "Alaskan Klee Kai",link: "https://www.akc.org/dog-breeds/alaskan-klee-kai/"},
    {name: "Alaskan Malamute",link: "https://www.akc.org/dog-breeds/alaskan-malamute/"},
    {name: "American Bulldog",link: "https://www.akc.org/dog-breeds/american-bulldog/"},
    {name: "American English Coonhound",link: "https://www.akc.org/dog-breeds/american-english-coonhound/"},
    {name: "American Eskimo Dog",link: "https://www.akc.org/dog-breeds/american-eskimo-dog/"},
    {name: "American Foxhound",link: "https://www.akc.org/dog-breeds/american-foxhound/"},
    {name: "American Hairless Terrier",link: "https://www.akc.org/dog-breeds/american-hairless-terrier/"},
    {name: "American Leopard Hound",link: "https://www.akc.org/dog-breeds/american-leopard-hound/"},
    {name: "American Staffordshire Terrier",link: "https://www.akc.org/dog-breeds/american-staffordshire-terrier/"},
    {name: "American Water Spaniel",link: "https://www.akc.org/dog-breeds/american-water-spaniel/"},
    {name: "Anatolian Shepherd Dog",link: "https://www.akc.org/dog-breeds/anatolian-shepherd-dog/"},
    {name: "Appenzeller Sennenhund",link: "https://www.akc.org/dog-breeds/appenzeller-sennenhund/"},
    {name: "Australian Cattle Dog",link: "https://www.akc.org/dog-breeds/australian-cattle-dog/"},
    {name: "Australian Kelpie",link: "https://www.akc.org/dog-breeds/australian-kelpie/"},
    {name: "Australian Shepherd",link: "https://www.akc.org/dog-breeds/australian-shepherd/"},
    {name: "Australian Stumpy Tail Cattle Dog",link: "https://www.akc.org/dog-breeds/australian-stumpy-tail-cattle-dog/"},
    {name: "Australian Terrier",link: "https://www.akc.org/dog-breeds/australian-terrier/"},
    {name: "Azawakh",link: "https://www.akc.org/dog-breeds/azawakh/"},
    {name: "Barbado da Terceira",link: "https://www.akc.org/dog-breeds/barbado-da-terceira/"},
    {name: "Barbet",link: "https://www.akc.org/dog-breeds/barbet/"},
    {name: "Basenji",link: "https://www.akc.org/dog-breeds/basenji/"},
    {name: "Basset Fauve de Bretagne",link: "https://www.akc.org/dog-breeds/basset-fauve-de-bretagne/"},
    {name: "Basset Hound",link: "https://www.akc.org/dog-breeds/basset-hound/"},
    {name: "Bavarian Mountain Scent Hound",link: "https://www.akc.org/dog-breeds/bavarian-mountain-scent-hound/"},
    {name: "Beagle",link: "https://www.akc.org/dog-breeds/beagle/"},
    {name: "Bearded Collie",link: "https://www.akc.org/dog-breeds/bearded-collie/"},
    {name: "Beauceron",link: "https://www.akc.org/dog-breeds/beauceron/"},
    {name: "Bedlington Terrier",link: "https://www.akc.org/dog-breeds/bedlington-terrier/"},
    {name: "Belgian Laekenois",link: "https://www.akc.org/dog-breeds/belgian-laekenois/"},
    {name: "Belgian Malinois",link: "https://www.akc.org/dog-breeds/belgian-malinois/"},
    {name: "Belgian Sheepdog",link: "https://www.akc.org/dog-breeds/belgian-sheepdog/"},
    {name: "Belgian Tervuren",link: "https://www.akc.org/dog-breeds/belgian-tervuren/"},
    {name: "Bergamasco Sheepdog",link: "https://www.akc.org/dog-breeds/bergamasco-sheepdog/"},
    {name: "Berger Picard",link: "https://www.akc.org/dog-breeds/berger-picard/"},
    {name: "Bernese Mountain Dog",link: "https://www.akc.org/dog-breeds/bernese-mountain-dog/"},
    {name: "Bichon Frise",link: "https://www.akc.org/dog-breeds/bichon-frise/"},
    {name: "Biewer Terrier",link: "https://www.akc.org/dog-breeds/biewer-terrier/"},
    {name: "Black and Tan Coonhound",link: "https://www.akc.org/dog-breeds/black-and-tan-coonhound/"},
    {name: "Black Russian Terrier",link: "https://www.akc.org/dog-breeds/black-russian-terrier/"},
    {name: "Bloodhound",link: "https://www.akc.org/dog-breeds/bloodhound/"},
    {name: "Bluetick Coonhound",link: "https://www.akc.org/dog-breeds/bluetick-coonhound/"},
    {name: "Boerboel",link: "https://www.akc.org/dog-breeds/boerboel/"},
    {name: "Bohemian Shepherd",link: "https://www.akc.org/dog-breeds/bohemian-shepherd/"},
    {name: "Bolognese",link: "https://www.akc.org/dog-breeds/bolognese/"},
    {name: "Border Collie",link: "https://www.akc.org/dog-breeds/border-collie/"},
    {name: "Border Terrier",link: "https://www.akc.org/dog-breeds/border-terrier/"},
    {name: "Borzoi",link: "https://www.akc.org/dog-breeds/borzoi/"},
    {name: "Boston Terrier",link: "https://www.akc.org/dog-breeds/boston-terrier/"},
    {name: "Bouvier des Flandres",link: "https://www.akc.org/dog-breeds/bouvier-des-flandres/"},
    {name: "Boxer",link: "https://www.akc.org/dog-breeds/boxer/"},
    {name: "Boykin Spaniel",link: "https://www.akc.org/dog-breeds/boykin-spaniel/"},
    {name: "Bracco Italiano",link: "https://www.akc.org/dog-breeds/bracco-italiano/"},
    {name: "Braque du Bourbonnais",link: "https://www.akc.org/dog-breeds/braque-du-bourbonnais/"},
    {name: "Braque Francais Pyrenean",link: "https://www.akc.org/dog-breeds/braque-francais-pyrenean/"},
    {name: "Briard",link: "https://www.akc.org/dog-breeds/briard/"},
    {name: "Brittany",link: "https://www.akc.org/dog-breeds/brittany/"},
    {name: "Broholmer",link: "https://www.akc.org/dog-breeds/broholmer/"},
    {name: "Brussels Griffon",link: "https://www.akc.org/dog-breeds/brussels-griffon/"},
    {name: "Bull Terrier",link: "https://www.akc.org/dog-breeds/bull-terrier/"},
    {name: "Bulldog",link: "https://www.akc.org/dog-breeds/bulldog/"},
    {name: "Bullmastiff",link: "https://www.akc.org/dog-breeds/bullmastiff/"},
    {name: "Cairn Terrier",link: "https://www.akc.org/dog-breeds/cairn-terrier/"},
    {name: "Canaan Dog",link: "https://www.akc.org/dog-breeds/canaan-dog/"},
    {name: "Cane Corso",link: "https://www.akc.org/dog-breeds/cane-corso/"},
    {name: "Cardigan Welsh Corgi",link: "https://www.akc.org/dog-breeds/cardigan-welsh-corgi/"},
    {name: "Carolina Dog",link: "https://www.akc.org/dog-breeds/carolina-dog/"},
    {name: "Catahoula Leopard Dog",link: "https://www.akc.org/dog-breeds/catahoula-leopard-dog/"},
    {name: "Caucasian Shepherd Dog",link: "https://www.akc.org/dog-breeds/caucasian-shepherd-dog/"},
    {name: "Cavalier King Charles Spaniel",link: "https://www.akc.org/dog-breeds/cavalier-king-charles-spaniel/"},
    {name: "Central Asian Shepherd Dog",link: "https://www.akc.org/dog-breeds/central-asian-shepherd-dog/"},
    {name: "Cesky Terrier",link: "https://www.akc.org/dog-breeds/cesky-terrier/"},
    {name: "Chesapeake Bay Retriever",link: "https://www.akc.org/dog-breeds/chesapeake-bay-retriever/"},
    {name: "Chihuahua",link: "https://www.akc.org/dog-breeds/chihuahua/"},
    {name: "Chinese Crested",link: "https://www.akc.org/dog-breeds/chinese-crested/"},
    {name: "Chinese Shar-Pei",link: "https://www.akc.org/dog-breeds/chinese-shar-pei/"},
    {name: "Chinook",link: "https://www.akc.org/dog-breeds/chinook/"},
    {name: "Chow Chow",link: "https://www.akc.org/dog-breeds/chow-chow/"},
    {name: "Cirneco dell’Etna",link: "https://www.akc.org/dog-breeds/cirneco-delletna/"},
    {name: "Clumber Spaniel",link: "https://www.akc.org/dog-breeds/clumber-spaniel/"},
    {name: "Cocker Spaniel",link: "https://www.akc.org/dog-breeds/cocker-spaniel/"},
    {name: "Collie",link: "https://www.akc.org/dog-breeds/collie/"},
    {name: "Coton de Tulear",link: "https://www.akc.org/dog-breeds/coton-de-tulear/"},
    {name: "Croatian Sheepdog",link: "https://www.akc.org/dog-breeds/croatian-sheepdog/"},
    {name: "Curly-Coated Retriever",link: "https://www.akc.org/dog-breeds/curly-coated-retriever/"},
    {name: "Czechoslovakian Vlcak",link: "https://www.akc.org/dog-breeds/czechoslovakian-vlcak/"},
    {name: "Dachshund",link: "https://www.akc.org/dog-breeds/dachshund/"},
    {name: "Dalmatian",link: "https://www.akc.org/dog-breeds/dalmatian/"},
    {name: "Dandie Dinmont Terrier",link: "https://www.akc.org/dog-breeds/dandie-dinmont-terrier/"},
    {name: "Danish-Swedish Farmdog",link: "https://www.akc.org/dog-breeds/danish-swedish-farmdog/"},
    {name: "Deutscher Wachtelhund",link: "https://www.akc.org/dog-breeds/deutscher-wachtelhund/"},
    {name: "Doberman Pinscher",link: "https://www.akc.org/dog-breeds/doberman-pinscher/"},
    {name: "Dogo Argentino",link: "https://www.akc.org/dog-breeds/dogo-argentino/"},
    {name: "Dogue de Bordeaux",link: "https://www.akc.org/dog-breeds/dogue-de-bordeaux/"},
    {name: "Drentsche Patrijshond",link: "https://www.akc.org/dog-breeds/drentsche-patrijshond/"},
    {name: "Drever",link: "https://www.akc.org/dog-breeds/drever/"},
    {name: "Dutch Shepherd",link: "https://www.akc.org/dog-breeds/dutch-shepherd/"},
    {name: "English Cocker Spaniel",link: "https://www.akc.org/dog-breeds/english-cocker-spaniel/"},
    {name: "English Foxhound",link: "https://www.akc.org/dog-breeds/english-foxhound/"},
    {name: "English Setter",link: "https://www.akc.org/dog-breeds/english-setter/"},
    {name: "English Springer Spaniel",link: "https://www.akc.org/dog-breeds/english-springer-spaniel/"},
    {name: "English Toy Spaniel",link: "https://www.akc.org/dog-breeds/english-toy-spaniel/"},
    {name: "Entlebucher Mountain Dog",link: "https://www.akc.org/dog-breeds/entlebucher-mountain-dog/"},
    {name: "Estrela Mountain Dog",link: "https://www.akc.org/dog-breeds/estrela-mountain-dog/"},
    {name: "Eurasier",link: "https://www.akc.org/dog-breeds/eurasier/"},
    {name: "Field Spaniel",link: "https://www.akc.org/dog-breeds/field-spaniel/"},
    {name: "Finnish Lapphund",link: "https://www.akc.org/dog-breeds/finnish-lapphund/"},
    {name: "Finnish Spitz",link: "https://www.akc.org/dog-breeds/finnish-spitz/"},
    {name: "Flat-Coated Retriever",link: "https://www.akc.org/dog-breeds/flat-coated-retriever/"},
    {name: "French Bulldog",link: "https://www.akc.org/dog-breeds/french-bulldog/"},
    {name: "French Spaniel",link: "https://www.akc.org/dog-breeds/french-spaniel/"},
    {name: "German Longhaired Pointer",link: "https://www.akc.org/dog-breeds/german-longhaired-pointer/"},
    {name: "German Pinscher",link: "https://www.akc.org/dog-breeds/german-pinscher/"},
    {name: "German Shepherd Dog",link: "https://www.akc.org/dog-breeds/german-shepherd-dog/"},
    {name: "German Shorthaired Pointer",link: "https://www.akc.org/dog-breeds/german-shorthaired-pointer/"},
    {name: "German Spitz",link: "https://www.akc.org/dog-breeds/german-spitz/"},
    {name: "German Wirehaired Pointer",link: "https://www.akc.org/dog-breeds/german-wirehaired-pointer/"},
    {name: "Giant Schnauzer",link: "https://www.akc.org/dog-breeds/giant-schnauzer/"},
    {name: "Glen of Imaal Terrier",link: "https://www.akc.org/dog-breeds/glen-of-imaal-terrier/"},
    {name: "Golden Retriever",link: "https://www.akc.org/dog-breeds/golden-retriever/"},
    {name: "Gordon Setter",link: "https://www.akc.org/dog-breeds/gordon-setter/"},
    {name: "Grand Basset Griffon Vendéen",link: "https://www.akc.org/dog-breeds/grand-basset-griffon-vendeen/"},
    {name: "Great Dane",link: "https://www.akc.org/dog-breeds/great-dane/"},
    {name: "Great Pyrenees",link: "https://www.akc.org/dog-breeds/great-pyrenees/"},
    {name: "Greater Swiss Mountain Dog",link: "https://www.akc.org/dog-breeds/greater-swiss-mountain-dog/"},
    {name: "Greyhound",link: "https://www.akc.org/dog-breeds/greyhound/"},
    {name: "Hamiltonstovare",link: "https://www.akc.org/dog-breeds/hamiltonstovare/"},
    {name: "Hanoverian Scenthound",link: "https://www.akc.org/dog-breeds/hanoverian-scenthound/"},
    {name: "Harrier",link: "https://www.akc.org/dog-breeds/harrier/"},
    {name: "Havanese",link: "https://www.akc.org/dog-breeds/havanese/"},
    {name: "Hokkaido",link: "https://www.akc.org/dog-breeds/hokkaido/"},
    {name: "Hovawart",link: "https://www.akc.org/dog-breeds/hovawart/"},
    {name: "Ibizan Hound",link: "https://www.akc.org/dog-breeds/ibizan-hound/"},
    {name: "Icelandic Sheepdog",link: "https://www.akc.org/dog-breeds/icelandic-sheepdog/"},
    {name: "Irish Red and White Setter",link: "https://www.akc.org/dog-breeds/irish-red-and-white-setter/"},
    {name: "Irish Setter",link: "https://www.akc.org/dog-breeds/irish-setter/"},
    {name: "Irish Terrier",link: "https://www.akc.org/dog-breeds/irish-terrier/"},
    {name: "Irish Water Spaniel",link: "https://www.akc.org/dog-breeds/irish-water-spaniel/"},
    {name: "Irish Wolfhound",link: "https://www.akc.org/dog-breeds/irish-wolfhound/"},
    {name: "Italian Greyhound",link: "https://www.akc.org/dog-breeds/italian-greyhound/"},
    {name: "Jagdterrier",link: "https://www.akc.org/dog-breeds/jagdterrier/"},
    {name: "Japanese Akitainu",link: "https://www.akc.org/dog-breeds/japanese-akitainu/"},
    {name: "Japanese Chin",link: "https://www.akc.org/dog-breeds/japanese-chin/"},
    {name: "Japanese Spitz",link: "https://www.akc.org/dog-breeds/japanese-spitz/"},
    {name: "Japanese Terrier",link: "https://www.akc.org/dog-breeds/japanese-terrier/"},
    {name: "Jindo",link: "https://www.akc.org/dog-breeds/jindo/"},
    {name: "Kai Ken",link: "https://www.akc.org/dog-breeds/kai-ken/"},
    {name: "Karelian Bear Dog",link: "https://www.akc.org/dog-breeds/karelian-bear-dog/"},
    {name: "Keeshond",link: "https://www.akc.org/dog-breeds/keeshond/"},
    {name: "Kerry Blue Terrier",link: "https://www.akc.org/dog-breeds/kerry-blue-terrier/"},
    {name: "Kishu Ken",link: "https://www.akc.org/dog-breeds/kishu-ken/"},
    {name: "Komondor",link: "https://www.akc.org/dog-breeds/komondor/"},
    {name: "Kromfohrlander",link: "https://www.akc.org/dog-breeds/kromfohrlander/"},
    {name: "Kuvasz",link: "https://www.akc.org/dog-breeds/kuvasz/"},
    {name: "Labrador Retriever",link: "https://www.akc.org/dog-breeds/labrador-retriever/"},
    {name: "Lagotto Romagnolo",link: "https://www.akc.org/dog-breeds/lagotto-romagnolo/"},
    {name: "Lakeland Terrier",link: "https://www.akc.org/dog-breeds/lakeland-terrier/"},
    {name: "Lancashire Heeler",link: "https://www.akc.org/dog-breeds/lancashire-heeler/"},
    {name: "Lapponian Herder",link: "https://www.akc.org/dog-breeds/lapponian-herder/"},
    {name: "Leonberger",link: "https://www.akc.org/dog-breeds/leonberger/"},
    {name: "Lhasa Apso",link: "https://www.akc.org/dog-breeds/lhasa-apso/"},
    {name: "Löwchen",link: "https://www.akc.org/dog-breeds/lowchen/"},
    {name: "Maltese",link: "https://www.akc.org/dog-breeds/maltese/"},
    {name: "Manchester Terrier (Standard)",link: "https://www.akc.org/dog-breeds/manchester-terrier-standard/"},
    {name: "Manchester Terrier (Toy)",link: "https://www.akc.org/dog-breeds/manchester-terrier-toy/"},
    {name: "Mastiff",link: "https://www.akc.org/dog-breeds/mastiff/"},
    {name: "Miniature American Shepherd",link: "https://www.akc.org/dog-breeds/miniature-american-shepherd/"},
    {name: "Miniature Bull Terrier",link: "https://www.akc.org/dog-breeds/miniature-bull-terrier/"},
    {name: "Miniature Pinscher",link: "https://www.akc.org/dog-breeds/miniature-pinscher/"},
    {name: "Miniature Schnauzer",link: "https://www.akc.org/dog-breeds/miniature-schnauzer/"},
    {name: "Mountain Cur",link: "https://www.akc.org/dog-breeds/mountain-cur/"},
    {name: "Mudi",link: "https://www.akc.org/dog-breeds/mudi/"},
    {name: "Neapolitan Mastiff",link: "https://www.akc.org/dog-breeds/neapolitan-mastiff/"},
    {name: "Nederlandse Kooikerhondje",link: "https://www.akc.org/dog-breeds/nederlandse-kooikerhondje/"},
    {name: "Newfoundland",link: "https://www.akc.org/dog-breeds/newfoundland/"},
    {name: "Norfolk Terrier",link: "https://www.akc.org/dog-breeds/norfolk-terrier/"},
    {name: "Norrbottenspets",link: "https://www.akc.org/dog-breeds/norrbottenspets/"},
    {name: "Norwegian Buhund",link: "https://www.akc.org/dog-breeds/norwegian-buhund/"},
    {name: "Norwegian Elkhound",link: "https://www.akc.org/dog-breeds/norwegian-elkhound/"},
    {name: "Norwegian Lundehund",link: "https://www.akc.org/dog-breeds/norwegian-lundehund/"},
    {name: "Norwich Terrier",link: "https://www.akc.org/dog-breeds/norwich-terrier/"},
    {name: "Nova Scotia Duck Tolling Retriever",link: "https://www.akc.org/dog-breeds/nova-scotia-duck-tolling-retriever/"},
    {name: "Old English Sheepdog",link: "https://www.akc.org/dog-breeds/old-english-sheepdog/"},
    {name: "Otterhound",link: "https://www.akc.org/dog-breeds/otterhound/"},
    {name: "Papillon",link: "https://www.akc.org/dog-breeds/papillon/"},
    {name: "Parson Russell Terrier",link: "https://www.akc.org/dog-breeds/parson-russell-terrier/"},
    {name: "Pekingese",link: "https://www.akc.org/dog-breeds/pekingese/"},
    {name: "Pembroke Welsh Corgi",link: "https://www.akc.org/dog-breeds/pembroke-welsh-corgi/"},
    {name: "Perro de Presa Canario",link: "https://www.akc.org/dog-breeds/perro-de-presa-canario/"},
    {name: "Peruvian Inca Orchid",link: "https://www.akc.org/dog-breeds/peruvian-inca-orchid/"},
    {name: "Petit Basset Griffon Vendéen",link: "https://www.akc.org/dog-breeds/petit-basset-griffon-vendeen/"},
    {name: "Pharaoh Hound",link: "https://www.akc.org/dog-breeds/pharaoh-hound/"},
    {name: "Plott Hound",link: "https://www.akc.org/dog-breeds/plott-hound/"},
    {name: "Pointer",link: "https://www.akc.org/dog-breeds/pointer/"},
    {name: "Polish Lowland Sheepdog",link: "https://www.akc.org/dog-breeds/polish-lowland-sheepdog/"},
    {name: "Pomeranian",link: "https://www.akc.org/dog-breeds/pomeranian/"},
    {name: "Poodle (Miniature)",link: "https://www.akc.org/dog-breeds/poodle-miniature/"},
    {name: "Poodle (Standard)",link: "https://www.akc.org/dog-breeds/poodle-standard/"},
    {name: "Poodle (Toy)",link: "https://www.akc.org/dog-breeds/poodle-toy/"},
    {name: "Porcelaine",link: "https://www.akc.org/dog-breeds/porcelaine/"},
    {name: "Portuguese Podengo",link: "https://www.akc.org/dog-breeds/portuguese-podengo/"},
    {name: "Portuguese Podengo Pequeno",link: "https://www.akc.org/dog-breeds/portuguese-podengo-pequeno/"},
    {name: "Portuguese Pointer",link: "https://www.akc.org/dog-breeds/portuguese-pointer/"},
    {name: "Portuguese Sheepdog",link: "https://www.akc.org/dog-breeds/portuguese-sheepdog/"},
    {name: "Portuguese Water Dog",link: "https://www.akc.org/dog-breeds/portuguese-water-dog/"},
    {name: "Pudelpointer",link: "https://www.akc.org/dog-breeds/pudelpointer/"},
    {name: "Pug",link: "https://www.akc.org/dog-breeds/pug/"},
    {name: "Puli",link: "https://www.akc.org/dog-breeds/puli/"},
    {name: "Pumi",link: "https://www.akc.org/dog-breeds/pumi/"},
    {name: "Pyrenean Mastiff",link: "https://www.akc.org/dog-breeds/pyrenean-mastiff/"},
    {name: "Pyrenean Shepherd",link: "https://www.akc.org/dog-breeds/pyrenean-shepherd/"},
    {name: "Rafeiro do Alentejo",link: "https://www.akc.org/dog-breeds/rafeiro-do-alentejo/"},
    {name: "Rat Terrier",link: "https://www.akc.org/dog-breeds/rat-terrier/"},
    {name: "Redbone Coonhound",link: "https://www.akc.org/dog-breeds/redbone-coonhound/"},
    {name: "Rhodesian Ridgeback",link: "https://www.akc.org/dog-breeds/rhodesian-ridgeback/"},
    {name: "Romanian Carpathian Shepherd",link: "https://www.akc.org/dog-breeds/romanian-carpathian-shepherd/"},
    {name: "Romanian Mioritic Shepherd Dog",link: "https://www.akc.org/dog-breeds/romanian-mioritic-shepherd-dog/"},
    {name: "Rottweiler",link: "https://www.akc.org/dog-breeds/rottweiler/"},
    {name: "Russell Terrier",link: "https://www.akc.org/dog-breeds/russell-terrier/"},
    {name: "Russian Toy",link: "https://www.akc.org/dog-breeds/russian-toy/"},
    {name: "Russian Tsvetnaya Bolonka",link: "https://www.akc.org/dog-breeds/russian-tsvetnaya-bolonka/"},
    {name: "Saint Bernard",link: "https://www.akc.org/dog-breeds/st-bernard/"},
    {name: "Saluki",link: "https://www.akc.org/dog-breeds/saluki/"},
    {name: "Samoyed",link: "https://www.akc.org/dog-breeds/samoyed/"},
    {name: "Schapendoes",link: "https://www.akc.org/dog-breeds/schapendoes/"},
    {name: "Schipperke",link: "https://www.akc.org/dog-breeds/schipperke/"},
    {name: "Scottish Deerhound",link: "https://www.akc.org/dog-breeds/scottish-deerhound/"},
    {name: "Scottish Terrier",link: "https://www.akc.org/dog-breeds/scottish-terrier/"},
    {name: "Sealyham Terrier",link: "https://www.akc.org/dog-breeds/sealyham-terrier/"},
    {name: "Segugio Italiano",link: "https://www.akc.org/dog-breeds/segugio-italiano/"},
    {name: "Shetland Sheepdog",link: "https://www.akc.org/dog-breeds/shetland-sheepdog/"},
    {name: "Shiba Inu",link: "https://www.akc.org/dog-breeds/shiba-inu/"},
    {name: "Shih Tzu",link: "https://www.akc.org/dog-breeds/shih-tzu/"},
    {name: "Shikoku",link: "https://www.akc.org/dog-breeds/shikoku/"},
    {name: "Siberian Husky",link: "https://www.akc.org/dog-breeds/siberian-husky/"},
    {name: "Silky Terrier",link: "https://www.akc.org/dog-breeds/silky-terrier/"},
    {name: "Skye Terrier",link: "https://www.akc.org/dog-breeds/skye-terrier/"},
    {name: "Sloughi",link: "https://www.akc.org/dog-breeds/sloughi/"},
    {name: "Slovakian Wirehaired Pointer",link: "https://www.akc.org/dog-breeds/slovakian-wirehaired-pointer/"},
    {name: "Slovensky Cuvac",link: "https://www.akc.org/dog-breeds/slovensky-cuvac/"},
    {name: "Slovensky Kopov",link: "https://www.akc.org/dog-breeds/slovensky-kopov/"},
    {name: "Small Munsterlander",link: "https://www.akc.org/dog-breeds/small-munsterlander/"},
    {name: "Smooth Fox Terrier",link: "https://www.akc.org/dog-breeds/smooth-fox-terrier/"},
    {name: "Soft Coated Wheaten Terrier",link: "https://www.akc.org/dog-breeds/soft-coated-wheaten-terrier/"},
    {name: "Spanish Mastiff",link: "https://www.akc.org/dog-breeds/spanish-mastiff/"},
    {name: "Spanish Water Dog",link: "https://www.akc.org/dog-breeds/spanish-water-dog/"},
    {name: "Spinone Italiano",link: "https://www.akc.org/dog-breeds/spinone-italiano/"},
    {name: "Stabyhoun",link: "https://www.akc.org/dog-breeds/stabyhoun/"},
    {name: "Staffordshire Bull Terrier",link: "https://www.akc.org/dog-breeds/staffordshire-bull-terrier/"},
    {name: "Standard Schnauzer",link: "https://www.akc.org/dog-breeds/standard-schnauzer/"},
    {name: "Sussex Spaniel",link: "https://www.akc.org/dog-breeds/sussex-spaniel/"},
    {name: "Swedish Lapphund",link: "https://www.akc.org/dog-breeds/swedish-lapphund/"},
    {name: "Swedish Vallhund",link: "https://www.akc.org/dog-breeds/swedish-vallhund/"},
    {name: "Taiwan Dog",link: "https://www.akc.org/dog-breeds/taiwan-dog/"},
    {name: "Teddy Roosevelt Terrier",link: "https://www.akc.org/dog-breeds/teddy-roosevelt-terrier/"},
    {name: "Thai Ridgeback",link: "https://www.akc.org/dog-breeds/thai-ridgeback/"},
    {name: "Tibetan Mastiff",link: "https://www.akc.org/dog-breeds/tibetan-mastiff/"},
    {name: "Tibetan Spaniel",link: "https://www.akc.org/dog-breeds/tibetan-spaniel/"},
    {name: "Tibetan Terrier",link: "https://www.akc.org/dog-breeds/tibetan-terrier/"},
    {name: "Tornjak",link: "https://www.akc.org/dog-breeds/tornjak/"},
    {name: "Tosa",link: "https://www.akc.org/dog-breeds/tosa/"},
    {name: "Toy Fox Terrier",link: "https://www.akc.org/dog-breeds/toy-fox-terrier/"},
    {name: "Transylvanian Hound",link: "https://www.akc.org/dog-breeds/transylvanian-hound/"},
    {name: "Treeing Tennessee Brindle",link: "https://www.akc.org/dog-breeds/treeing-tennessee-brindle/"},
    {name: "Treeing Walker Coonhound",link: "https://www.akc.org/dog-breeds/treeing-walker-coonhound/"},
    {name: "Vizsla",link: "https://www.akc.org/dog-breeds/vizsla/"},
    {name: "Volpino Italiano",link: "https://www.akc.org/dog-breeds/volpino-italiano/"},
    {name: "Weimaraner",link: "https://www.akc.org/dog-breeds/weimaraner/"},
    {name: "Welsh Springer Spaniel",link: "https://www.akc.org/dog-breeds/welsh-springer-spaniel/"},
    {name: "Welsh Terrier",link: "https://www.akc.org/dog-breeds/welsh-terrier/"},
    {name: "West Highland White Terrier",link: "https://www.akc.org/dog-breeds/west-highland-white-terrier/"},
    {name: "Wetterhoun",link: "https://www.akc.org/dog-breeds/wetterhoun/"},
    {name: "Whippet",link: "https://www.akc.org/dog-breeds/whippet/"},
    {name: "Wire Fox Terrier",link: "https://www.akc.org/dog-breeds/wire-fox-terrier/"},
    {name: "Wirehaired Pointing Griffon",link: "https://www.akc.org/dog-breeds/wirehaired-pointing-griffon/"},
    {name: "Wirehaired Vizsla",link: "https://www.akc.org/dog-breeds/wirehaired-vizsla/"},
    {name: "Working Kelpie",link: "https://www.akc.org/dog-breeds/working-kelpie/"},
    {name: "Xoloitzcuintli",link: "https://www.akc.org/dog-breeds/xoloitzcuintli/"},
    {name: "Yakutian Laika",link: "https://www.akc.org/dog-breeds/yakutian-laika/"},
    {name: "Yorkshire Terrier",link: "https://www.akc.org/dog-breeds/yorkshire-terrier/"},
]

let input = document.querySelector("#search")
let listItems = document.querySelector("#list-items")
let button = document.querySelector("#all-dogs")

function populateListItems() {
    const searchValue = input.value.toLowerCase()
    let output = ""
    dogBreeds.forEach(breed => {
        breed.name.toLowerCase().includes(searchValue) ? output += `<li><a href="${breed.link}" target=blank>${breed.name}</a></li>` :  false;
    })
    listItems.innerHTML = output
}

input.addEventListener('keyup', function() {
    console.log('here is the input value: ', input.value)
    populateListItems()
})

button.addEventListener('click', populateListItems)